/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CellForm: typeof import('./src/components/cellForm.vue')['default']
    Empty: typeof import('./src/components/empty.vue')['default']
    Form: typeof import('./src/components/form.vue')['default']
    IconRight: typeof import('./src/components/iconRight.vue')['default']
    ImgList: typeof import('./src/components/imgList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTable: typeof import('./src/components/scrollTable.vue')['default']
  }
}
